version: '2'
networks:
  app-tier:
    driver: bridge

services:
    mariadb:
      image: 'bitnami/mariadb:latest'
      labels:
        kompose.service.type: nodeport
      environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - MARIADB_USER=my_user
          - MARIADB_DATABASE=my_database
          - MARIADB_PASSWORD=my_password
      networks:
        - app-tier
      ports:
        - '3306:3306'
    phpfpm:
        tty: true #Enables debugging capabilities when attached to this container.
        image: 'bitnami/php-fpm:latest'
        depends_on:
          - mariadb
        networks:
          - app-tier
        volumes:
          - ./public/:/app
          - ./config/php.ini:/opt/bitnami/php/etc/conf.d/custom.ini
        ports:
          - "9000:9000"
    nginx:
     image: 'bitnami/nginx:latest'
     depends_on:
       - phpfpm
     networks:
       - app-tier
     ports:
       - '80:8080'
       - '443:8443'
     volumes:
       - ./config/vhost.conf:/bitnami/nginx/conf/vhosts/localhost.conf





