version: '2'
networks:
  app-tier:
    driver: bridge

services:
    nginx-php-fpm:
      volumes:
        - test-native-osx-sync:/var/www/html:nocopy

volumes:
  test-native-osx-sync:
    external: true
