version: '2'
networks:
  app-tier:
    driver: bridge

services:
    mariadb:
      image: 'bitnami/mariadb:latest'
      labels:
        kompose.service.type: nodeport
      environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - MARIADB_USER=my_user
          - MARIADB_DATABASE=my_database
          - MARIADB_PASSWORD=my_password
      networks:
        - app-tier
      ports:
        - '3306:3306'
    nginx-php-fpm:
      image: richarvey/nginx-php-fpm:latest
      restart: always
      depends_on:
        - mariadb
      networks:
        - app-tier
      volumes:
        - ./public/:/var/www/html
        - ./config/php.ini:/usr/local/etc/php/conf.d/docker-vars.ini
        - ./config/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf
        - ./config/nginx.conf:/etc/nginx/sites-available/default.conf
      ports:
          - '80:80'
